import {StyleSheet, Dimensions} from 'react-native';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;
const styles = StyleSheet.create({
  main1: {
    width: '100%',
    height: '100%',
    flex: 1,
  },
  main2: {
    height: '25%',
    width: '100%',
  },
  main3: {
    height: '45%',
    width: '100%',
    backgroundColor: 'F5F5F5',
    paddingTop: 25,
  },
  main4: {
    height: '30%',
  },
  main5: {
    flex: 1,
    height: '30%',
    top: 30,
  },
  red1: {
    flex: 1,
  },
  red2: {
    with: '100%',
    height: 170,
  },
  red3: {
    width: '100%',
    flex: 1,
    height: '25%',
    backgroundColor: '#FE724C',
    justifyContent: 'center',
    alignItems: 'center',
  },
  red4: {
    fontSize: 50,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  red5: {
    height: '25%',
    flexDirection: 'row',
  },
  red6: {
    width: '50%',
    height: '100%',
    justifyContent: 'center',
    alignContent: 'center',
  },
  red7: {
    fontSize: 20,
    textAlign: 'center',
    color: '#FE724C',
  },
  red8: {
    position: 'absolute',
    justifyContent: 'center',
    alignContent: 'center',
    bottom: 0,
    height: 3,
    width: '100%',
    backgroundColor: '#FE724C',
  },
  red9: {
    width: '50%',
    height: '100%',
    justifyContent: 'center',
    alignContent: 'center',
  },
  red10: {
    fontSize: 20,
    color: '#FE724C',
    textAlign: 'center',
  },
  gr1: {
    top: 30,
    height: '100%',
    width: '100%',
    justifyContent: 'center',
    alignContent: 'center',
  },
  gr2: {
    fontSize: 20,
    marginLeft: 30,
    fontWeight: '600',
  },
  gr3: {
    width: windowWidth - 60,
    marginLeft: 30,
    backgroundColor: 'white',
    height: 45,
    marginTop: 20,
    flexDirection: 'row',
    alignContent: 'center',
    borderWidth: 1,
    borderColor: '#FE724C',
    borderRadius: 10,
  },
  gr4: {
    width: 30,
    height: 30,
    marginLeft: 15,
    marginTop: 8,
    justifyContent: 'center',
    alignContent: 'center',
  },
  gr5: {
    height: '100%',
    flex: 1,
    marginLeft: 10,
    fontSize: 20,
  },
  gr6: {
    width: 30,
    height: 20,
    marginLeft: 15,
    marginTop: 12,
  },
  gr7: {
    height: '100%',
    flex: 1,
    marginLeft: 10,
    fontSize: 16,
  },
  gr8: {
    height: '100%',
    aspectRatio: 1,
    justifyContent: 'center',
    alignContent: 'center',
  },
  gr9: {
    height: 15,
    width: 20,
  },
  gr10: {
    width: windowWidth - 60,
    marginLeft: 30,
    height: 30,
    marginTop: 20,
    flexDirection: 'row',
    alignContent: 'center',
  },
  gr11: {
    position: 'absolute',
    right: 0,
  },
  gr12: {
    color: 'black',
    position: 'absolute',
    right: 0,
  },
  gr13: {
    width: windowWidth - 60,
    height: 50,
    backgroundColor: '#FE724C',
    marginLeft: 30,
    marginTop: 10,
    borderRadius: 100,
    justifyContent: 'center',
    alignContent: 'center',
  },
  gr14: {
    color: 'white',
    fontSize: 16,
    fontWeight: '500',
    textAlign: 'center',
  },
  bl1: {
    width: '100%',
    height: '100%',
  },
  bl2: {
    top: 40,
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'center',
    height: 40,
    width: windowWidth - 60,
    marginLeft: 30,
  },
  bl3: {
    height: 1,
    width: '30%',
    backgroundColor: 'black',
  },
  bl4: {
    height: 1,
    width: '30%',
    backgroundColor: 'black',
    alignContent: 'center',
    justifyContent: 'center',
  },
  bl5: {
    top: 35,
    height: 50,
    width: windowWidth - 60,
    marginLeft: 30,
    marginTop: 20,
    flexDirection: 'row',
  },
  bl6: {
    width: 0.5 * (windowWidth - 60) - 3,
    height: '100%',
  },
  bl7: {
    width: 0.5 * (windowWidth - 60) - 3,
    height: '100%',
    marginLeft: 6,
  },
});

export default styles;
